### PR TITLE
Necessary features and fixes required for base Signify functionality

### LINKED ISSUE #2: Config is set separately in BaseIndex after already being set on SolrCoreService
In the BaseIndex `__construct` function, the config is reset to the yaml settings when it's also already set when the SolrCoreService is created. This means the client options are being set twice when they don't need to be, and also makes it harder to override the yaml settings if that's required (e.g. to replace some with environment variables).
lines 109-112:
``` php
$config = Config::inst()->get(SolrCoreService::class, 'config');
$config['endpoint'] = $this->getConfig($config['endpoint']);
$this->client = (new SolrCoreService())->getClient();
$this->client->setOptions($config);
```
Instead, the options already set once when the SolrCoreService is created can be used as the base that the 'endpoint' is added to. This makes sure that any changes to the SolrCoreService are reflected in the Index.

### LINKED ISSUE #3: SpellcheckRetry should be optional
The `doSearch` function in BaseIndex will always follow the spellcheck suggestions if spellcheck is turned on and the results are empty, but this is not always the preferred behaviour.

This is particularly problematic in combination with synonyms, where the original search term has no results itself, which means a spellcheck suggestion can be returned, but if the original search term has results from an associated synonym then the results returned are _not_ from the spellcheck suggested term.

There is a `followSpellcheck` option on the BaseQuery, but this appears to be used to force following the spellcheck even when there are results for the original term, rather than allowing it when there are no results. There is a note with the relevant variable that implies this was not it's intended purpose, but documentation on the BaseIndex doRetry function is contradictory. 
BaseQuery - $followSpellcheck documentation:
``` php
/**
 * @var bool Follow spellchecking if there are no results
 */
 protected $followSpellcheck = false;
```
BaseIndex - doRetry() documentation:
``` php
\**
 * Check if the query should be retried with spellchecking
 * Conditions are:
 * It is not already a retry with spellchecking
 * Spellchecking is enabled
 * If spellchecking is enabled and nothing is found OR it should follow spellchecking none the less
 * There is a spellcheck output
 * /
```

Note: As-is, overriding the `spellcheckRetry` function to skip the retry means that the `updateSearchResults` extension point is skipped as it does not call `doSearch` again.

Expected behaviour: We should be able to get spellcheck _suggestions_ without necessarily following that suggestion when the original term has no results. If the `$followSpellcheck` setting is meant to apply only if there are no results, then the `doRetry` function should reflect that; or if the `$followSpellcheck` setting is meant to apply even if there are results, then the documentation for the variable should reflect that and an additional setting should be added to allow better control of the spellcheck behaviour.

### LINKED ISSUE #4: Changing page type creates duplicate record in index
When an existing page is already in the index and then the page type is changed, this creates a new record in the index without removing the old one. This means that the page can appear twice in search results, and that the previous version of the page becomes disconnected from any real record so it can never be updated or deleted without a full re-index.

Expected behaviour: when a page type changes, the previous record should be removed from the index before the new record is created.

### LINKED ISSUE #5: Fix permissions for admin area
Some content authors may need access to the 'Synonyms' tab in the 'Search' admin area of the CMS, but should not see the 'Solr Logs' and 'Dirty Classes' tabs.

Currently, there are permission options available for 'View Solr logs' and 'Delete Solr logs' but these options are not used to determine whether a member can do those actions. There are no separate permissions for the other tabs in the admin area, and viewing the models does not inherit from the default "Access to 'Search' section" permission. This means that a Content Author can be given permission to access the section, and will be able to see all three tabs, but the gridfields in every tab will appear empty as they do not have permission to view the models.

**Expected behaviour**
- If a Member has access to the Search section, they should be able to see the Synonyms tab and the Synonym items without additional permissions.
- There should be additional permissions added to be able to view the 'Dirty Classes' - there should not be any permissions available to create/delete/edit these. If a Member does not have permissions to view the 'DirtyClass' objects, then they should not see the 'Dirty Classes' tab in the admin area.
- The existing permissions for delete and view Solr logs should be implemented to act as per their descriptions. If a Member does not have permissions to view 'SolrLog' objects, then they should not see the 'Solr Logs' tab in the admin area
- Optional - An additional permission could also be added for editing Synonyms. The view permission can inherit from the overall section permission, but there may be cases where it would be valid to give some Members permission to see the Synonyms without being able to edit them. If it's decided that this additional permission is not required then the edit/create/delete permissions for Synonyms should also inherit from the section permission.

### PR DESCRIPTION
**Pull request by sig-peggy**
Includes only the most basic changes needed to make the module function for Signify requirements. Changes include:

## Fixes
- Check for null values in `json_decode`
- Allow use of additional Solarium `addDocuments` options `overwrite` and `commitWithin` - can be set in config.
- Combine duplicated 'index' analyzers in the 'text' fieldtype in the Solr 9 `types.ss` file into one analyzer

## Features
-  Improve extension point flexibility: Add a new extension point for `SchemaFactory::getCopyFieldsDefinitions()` and include `$object` in existing `DocumentFactory::onBeforeAddDoc()` extension point
- Add the ability to set a list of classes to be excluded from being indexed, both via the `SolrIndexTask` or via the `DataObjectExtension`
- Change the tokenizer used on main text type fields from `WhitespaceTokenizerFactory` to `ClassicTokenizerFactory` to account for punctuation - see [Solr tokenizer options](https://solr.apache.org/guide/solr/latest/indexing-guide/tokenizers.htm)

## Additional fixes added to be included in the same release:
- Remove duplicating setting of config settings in index from yaml config to allow overriding only once - [issue #2](https://github.com/signify-nz/silverstripe-solr/issues/2)
- change followSpellcheck logic to reflect what variable documentation states - [issue #3](https://github.com/signify-nz/silverstripe-solr/issues/3)
- fix issue that created duplicate index record when page type was changed - [issue #4](https://github.com/signify-nz/silverstripe-solr/issues/4)
- fix permissions to correctly use existing permissions and add new permission levels - [issue #5](https://github.com/signify-nz/silverstripe-solr/issues/5)

### CODE REVIEW

**Review by sig-mmiddleton — APPROVED** [review]
Looks good to me.

**Comment by sig-peggy** [comment]
Merged in additional changes to be included in the same release. See updated initial comment for full details.

**Review by sig-mmiddleton — APPROVED** [review]
Looks good to me.

**Review by sig-mmiddleton — APPROVED** [review]
Tested fix locally and works as expected.

**Pull request merged**
